// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Formula = 1,
  BinaryExpression = 2,
  CompareOp = 3,
  Ampersand = 4,
  Power = 7,
  UnaryExpression = 8,
  PrimaryExpression = 9,
  VariableRef = 10,
  FunctionCall = 12,
  FunctionName = 13,
  ArgList = 15,
  Number = 17,
  String = 18,
  Boolean = 19,
  ParenExpression = 20
