// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {formulaHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$tQVQPOOO!PQPO'#CqO!jQPO'#ChOVQPO'#CpOOQO'#Ce'#CeOOQO'#Cv'#CvQVQPOOOVQPO'#CdOVQPO,58xOVQPO,58xOVQPO,58xOVQPO,58xO!oQPO,59SO!vQPO,59[OOQO-E6o-E6oOOQO,59O,59OO#xQPO1G.dO$zQPO1G.dO%RQPO1G.dO%YQPO1G.dO%aQPO'#CkOOQO1G.n1G.nO%kQPO1G.nOOQO1G.v1G.vOVQPO'#CrO%pQPO,59VOOQO7+$Y7+$YO%xQPO,59^OOQO-E6p-E6p",
  stateData: "&W~OiOS~OTVOYSO]QO^ROaSObSOcSO~ORYOSWOTZOUXOVXO~OYeX]eX^eXaeXbeXceXgeX~PnO^[O~OZeO~PVOZgO~PnOTZOUXOVXORQiYQi]Qi^QiaQibQicQigQiZQi`Qi~OSQi~P!}OVXORQiSQiTQiYQi]Qi^QiaQibQicQigQiZQi`Qi~OUQi~P$POSWO~P!}OUXO~P$PO`hOZ_X~PnOZjO~O`hOZ_a~OZfa`fa~PnOcR]~",
  goto: "#RkPPlPPPPPllPPxPP!UPPPPx!X!_PPP!eeTORUVWXYZ[heSORUVWXYZ[hRf[QUOR^UQidRliSPOUQ]RQ_VQ`WQaXQbYQcZQd[Rkh",
  nodeNames: "⚠ Formula BinaryExpression CompareOp Ampersand ArithOp ArithOp Power UnaryExpression PrimaryExpression VariableRef ) FunctionCall FunctionName ( ArgList , Number String Boolean ParenExpression",
  maxTerm: 26,
  nodeProps: [
    ["openedBy", 11,"("],
    ["closedBy", 14,")"]
  ],
  propSources: [formulaHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "/n~RwX^#lpq#lqr$ars$luv&`vw&ewx&jxy(Xyz(^z{&`{|(c|}(h}!O(c!O!P(m!P!Q&`!Q![)m!^!_*O!_!`$a!`!a*Z!b!c*c!c!h+T!h!i+f!i!v+T!v!w.]!w!}+T#Q#R/i#T#Y+T#Y#Z+f#Z#h+T#h#i.]#i#o+T#y#z#l$f$g#l#BY#BZ#l$IS$I_#l$I|$JO#l$JT$JU#l$KV$KW#l&FU&FV#l~#qYi~X^#lpq#l#y#z#l$f$g#l#BY#BZ#l$IS$I_#l$I|$JO#l$JT$JU#l$KV$KW#l&FU&FV#l~$dP!_!`$g~$lOR~~$oWOY$lZr$lrs%Xs#O$l#O#P%^#P;'S$l;'S;=`&Y<%lO$l~%^Ob~~%aRO;'S$l;'S;=`%j;=`O$l~%mXOY$lZr$lrs%Xs#O$l#O#P%^#P;'S$l;'S;=`&Y;=`<%l$l<%lO$l~&]P;=`<%l$l~&eOU~~&jOS~~&mWOY&jZw&jwx%Xx#O&j#O#P'V#P;'S&j;'S;=`(R<%lO&j~'YRO;'S&j;'S;=`'c;=`O&j~'fXOY&jZw&jwx%Xx#O&j#O#P'V#P;'S&j;'S;=`(R;=`<%l&j<%lO&j~(UP;=`<%l&j~(^O^~~(cOZ~~(hOT~~(mO`~~(pP!Q![(s~(xRa~!Q![(s!g!h)R#X#Y)R~)UR{|)_}!O)_!Q![)e~)bP!Q![)e~)jPa~!Q![)e~)rSa~!O!P(s!Q![)m!g!h)R#X#Y)R~*TQR~!_!`$g!`!a$g~*`PR~!_!`$g~*fR!c!}*o#R#S*o#T#o*o~*tTY~!O!P*o!Q![*o!c!}*o#R#S*o#T#o*o~+YS]~!Q![+T!c!}+T#R#S+T#T#o+T~+kU]~!Q![+T!c!d+}!d!}+T#R#S+T#T#U+}#U#o+T~,SW]~!Q![+T!c!n+T!n!o,l!o!}+T#R#S+T#T#`+T#`#a,l#a#o+T~,qW]~!Q![+T!c!u+T!u!v-Z!v!}+T#R#S+T#T#g+T#g#h-Z#h#o+T~-`W]~!Q![+T!c!g+T!g!h-x!h!}+T#R#S+T#T#X+T#X#Y-x#Y#o+T~.PSc~]~!Q![+T!c!}+T#R#S+T#T#o+T~.bW]~!Q![+T!c!t+T!t!u.z!u!}+T#R#S+T#T#f+T#f#g.z#g#o+T~/PW]~!Q![+T!c!w+T!w!x-Z!x!}+T#R#S+T#T#i+T#i#j-Z#j#o+T~/nOV~",
  tokenizers: [0],
  topRules: {"Formula":[0,1]},
  tokenPrec: 234
})
