/**
 * Type declarations for the generated Lezer parser.
 *
 * This file provides TypeScript types for the parser.js file
 * generated by @lezer/generator from formula.grammar.
 *
 * @module
 */

import type { LRParser } from '@lezer/lr';

/**
 * The generated Lezer parser for FormulaQ formula language.
 */
export const parser: LRParser;
